name: AMP Validation
on: push

jobs:
    amp_validation:
        name: AMP Validation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Install Node
              uses: guardian/actions-setup-node@main

            # Cache npm dependencies using https://github.com/bahmutov/npm-install
            - uses: bahmutov/npm-install@v1

            - name: Install
              run: yarn

            - name: Validate AMP
              run: make ampValidation
