name: Build Check
on: push

jobs:
    build_check:
        name: Build Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Install Node
              uses: guardian/actions-setup-node@main

            # Cache npm dependencies using https://github.com/bahmutov/npm-install
            - uses: bahmutov/npm-install@v1

            - name: Install
              run: yarn

            - name: Generate production build
              run: make build

            - name: Validate Build
              run: make buildCheck
