name: Run Lighthouse CI
on: [push]
jobs:
    lhci:
        name: Lighthouse
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1
            - name: Install Node
              uses: guardian/actions-setup-node@main
            - run: make build
            - name: Install and run Lighthouse CI
              env:
                  LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
              run: |
                  npm install -g puppeteer-core@2.1.0 @lhci/cli@0.7.0
                  lhci autorun
